// Copyright 2017-2024 @substrate-dev/dev-test authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @substrate-dev/node-dev

export const packageInfo = { name: '@substrate-dev/dev-test', path: 'auto', type: 'auto', version: '0.0.1' };
